heat_template_version: 2014-10-16
resources:
  userdata:
    type: OS::Heat::MultipartMime
    properties:
      parts:
      - config: {get_resource: swapon_config}
      - config: {get_resource: firstboot_config}
  firstboot_config:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      config: {get_file: /home/stack/templates/firstboot-setup.sh}
  swapon_config:
    type: OS::Heat::SoftwareConfig
    properties:
      config: |
        #!/bin/bash
        swap_device=
        if [[  &&  ]]; then
          rc_local="/etc/rc.d/rc.local"
          echo "swapon  " >> 
          chmod 755 
          swapon 
        fi
outputs:
  OS::stack_id:
    value: {get_resource: userdata}
